### ISSUE TITLE
how about using "CHILDREN" props in Btn.js

### ISSUE THREAD

**Issue by AmirAmirpoor** [ierfaaan/mafia-management#1]
hi there,
I think in Btn.js file instead of **props.value**, using **props.children** makes much more sense.
because then we can use Btn component similar to regular buttons. 
`<Button>click</Button> `
instead of
`<Button  value="click" />`

**Comment by BaseMax** [comment]
Hi

**Comment by ierfaaan** [comment]
Hi Amir, yes, you are right, thank you for your comment
